// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolManagementAppWeb.Data;

#nullable disable

namespace SchoolManagementAppWeb.Migrations.AuthDb
{
    [DbContext(typeof(AuthDatabaseContext))]
    partial class AuthDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "9f4b4f1d-b7a9-4019-a6fe-7af3ffc1bca3",
                            ConcurrencyStamp = "9f4b4f1d-b7a9-4019-a6fe-7af3ffc1bca3",
                            Name = "Student",
                            NormalizedName = "Student"
                        },
                        new
                        {
                            Id = "227927f4-33e4-4baa-9edb-a6631bca1227",
                            ConcurrencyStamp = "227927f4-33e4-4baa-9edb-a6631bca1227",
                            Name = "Educator",
                            NormalizedName = "Educator"
                        },
                        new
                        {
                            Id = "77c42450-7226-439b-92cd-bfc826d26cb6",
                            ConcurrencyStamp = "77c42450-7226-439b-92cd-bfc826d26cb6",
                            Name = "Admin",
                            NormalizedName = "Admin"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "d6a53300-8a84-4e49-b23a-ae7dd540d59c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "95eff7a9-ddbd-4f4b-b882-5a2a0c17ba3d",
                            Email = "director@ABCSchool.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "DIRECTOR@ABCSCHOOL.COM",
                            NormalizedUserName = "DIRECTOR@ABCSCHOOL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKKVOg/rCUbMKN91AeTvk0COPJi8MJYzOoOCmDAuVR5qdwWd03XdVf6T1VL2bp+Qlw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "77359465-3949-42dd-8e1c-6e9d0b3cdf0b",
                            TwoFactorEnabled = false,
                            UserName = "director@ABCSchool.com"
                        },
                        new
                        {
                            Id = "f523b7d8-ad00-4584-8c1e-4a0634f0ccdc",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "8e709290-07d5-4159-9758-b6fa609ddd44",
                            Email = "educator@ABCSchool.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "EDUCATOR@ABCSCHOOL.COM",
                            NormalizedUserName = "EDUCATOR@ABCSCHOOL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEL0D1pxyxkk+CaMZzL8CWMg1s5uF0Ms8+83gC/LIPw/TFtoOwZo+yWjKc6orc8cWEw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "33da5e19-90e3-43a4-8b3a-cd6a59dc2532",
                            TwoFactorEnabled = false,
                            UserName = "educator@ABCSchool.com"
                        },
                        new
                        {
                            Id = "eb2b606e-e91e-424a-8e4a-1590c018b3b9",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1b86381d-e08a-4f3a-86c1-fcd81906ea0c",
                            Email = "student@ABCSchool.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            NormalizedEmail = "STUDENT@ABCSCHOOL.COM",
                            NormalizedUserName = "STUDENT@ABCSCHOOL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEL52i4CYVzglrAbvUBGYevJS6flZ01ju5s4JSAVlx5OgTblzeS/9BLYLzKyv9hcdMg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7152fb8e-8532-4a2c-bcd4-cd9e46736aeb",
                            TwoFactorEnabled = false,
                            UserName = "student@ABCSchool.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "d6a53300-8a84-4e49-b23a-ae7dd540d59c",
                            RoleId = "77c42450-7226-439b-92cd-bfc826d26cb6"
                        },
                        new
                        {
                            UserId = "d6a53300-8a84-4e49-b23a-ae7dd540d59c",
                            RoleId = "227927f4-33e4-4baa-9edb-a6631bca1227"
                        },
                        new
                        {
                            UserId = "d6a53300-8a84-4e49-b23a-ae7dd540d59c",
                            RoleId = "9f4b4f1d-b7a9-4019-a6fe-7af3ffc1bca3"
                        },
                        new
                        {
                            UserId = "f523b7d8-ad00-4584-8c1e-4a0634f0ccdc",
                            RoleId = "227927f4-33e4-4baa-9edb-a6631bca1227"
                        },
                        new
                        {
                            UserId = "f523b7d8-ad00-4584-8c1e-4a0634f0ccdc",
                            RoleId = "9f4b4f1d-b7a9-4019-a6fe-7af3ffc1bca3"
                        },
                        new
                        {
                            UserId = "eb2b606e-e91e-424a-8e4a-1590c018b3b9",
                            RoleId = "9f4b4f1d-b7a9-4019-a6fe-7af3ffc1bca3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
