// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolManagementAppWeb.Data;

#nullable disable

namespace SchoolManagementAppWeb.Migrations
{
    [DbContext(typeof(SchoolApplicationDbContext))]
    [Migration("20251202085135_update Model Class and DBContext Class")]
    partial class updateModelClassandDBContextClass
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolManagementAppWeb.Models.EducatorDetailsEF", b =>
                {
                    b.Property<int>("educator_registration_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("educator_registration_Id"));

                    b.Property<string>("educator_address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("educator_class_assigned")
                        .HasColumnType("int");

                    b.Property<string>("educator_mobile_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("educator_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("educator_section_assigned")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("educator_subject_assigned")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("educator_registration_Id");

                    b.ToTable("EducatorDetailsEF");
                });

            modelBuilder.Entity("SchoolManagementAppWeb.Models.EducatorDetailsForDropdownEF", b =>
                {
                    b.Property<int>("educator_registration_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("educator_registration_Id"));

                    b.Property<string>("educator_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("educator_registration_Id");

                    b.ToTable("EducatorDetailsForDropdownEF");
                });

            modelBuilder.Entity("SchoolManagementAppWeb.Models.StudentDetailsEF", b =>
                {
                    b.Property<int>("student_registration_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("student_registration_Id"));

                    b.Property<string>("student_address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("student_class_details")
                        .HasColumnType("int");

                    b.Property<string>("student_guardian_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("student_mobile_number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("student_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("student_roll_number")
                        .HasColumnType("int");

                    b.Property<string>("student_section_details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("student_registration_Id");

                    b.ToTable("StudentDetailsEF");
                });

            modelBuilder.Entity("SchoolManagementAppWeb.Models.StudentDetailsForDropdownEF", b =>
                {
                    b.Property<int>("student_registration_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("student_registration_Id"));

                    b.Property<string>("student_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("student_registration_Id");

                    b.ToTable("StudentDetailsForDropdownEF");
                });
#pragma warning restore 612, 618
        }
    }
}
