// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SchoolManagementAppWeb.Data;

#nullable disable

namespace SchoolManagementAppWeb.Migrations
{
    [DbContext(typeof(StudentInfoDbContext))]
    [Migration("20251127152358_First- Creation of SchoolManagement App Databse")]
    partial class FirstCreationofSchoolManagementAppDatabse
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SchoolManagementAppWeb.Models.StudentDetailsForDropdown", b =>
                {
                    b.Property<int>("student_registration_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("student_registration_Id"));

                    b.Property<string>("student_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("student_registration_Id");

                    b.ToTable("StudentDetailsForDropdown");
                });

            modelBuilder.Entity("SchoolManagementAppWeb.Models.StudentInfo", b =>
                {
                    b.Property<int>("student_registration_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("student_registration_Id"));

                    b.Property<string>("student_address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("student_class")
                        .HasColumnType("int");

                    b.Property<string>("student_mobile_number")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("student_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("student_roll_number")
                        .HasColumnType("int");

                    b.Property<string>("student_section_name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("student_registration_Id");

                    b.ToTable("StudentInfo");
                });
#pragma warning restore 612, 618
        }
    }
}
